# Generated by Django 3.0.7 on 2020-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IN_Headline',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ML_Headline',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
    ]
