# Generated by Django 3.0.7 on 2020-06-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IN_Headline',
            new_name='INHeadline',
        ),
        migrations.RenameModel(
            old_name='ML_Headline',
            new_name='MLHeadline',
        ),
    ]
